### ISSUE TITLE
switching frequency and sinus frequency

### ISSUE THREAD

**Issue by aliaydin96** [aliaydin96/PWM_Generation#1]
@mesutto @furkankarakaya Merhabalar, 
 bu iki frekansi birbirinden ayri yapamadim. Bir yerde ikisi birbirini etkiliyor. Acaba bunlari nasil ayirabilirim?

**Comment by mesutto** [comment]
Detaylı bakmadan bir şey diyemem. Ama senin önce DSP'den bağımsız olarak bu iki frekansın ne anlama geldiğini anlaman gerekiyor. MATLAB'ta veya Simulink'te PWM ile sinüs üreten bir arkadaşla beraber çalışırsanız faydası olabilir.
